### ISSUE TITLE
Add DynamoDB support for ActiveRecord

### ISSUE THREAD

**Issue by pas256** [aws/aws-sdk-rails#1]
I just want my models to use DynamoDB, rather than MySQL or PostgreSQL via RDS. This was started in the v1 aws-sdk gem back in 2013, but never made it to maturity.

To simplify, Rails 4.2 and above.

**Comment by awood45** [comment]
This is feedback we're hearing from multiple customers, and I'm looking in to what that would look like for V2 of the SDK and the newer version of DynamoDB's API.

In the meantime, this gem was crafted so that you can also use V1 of the SDK in the same project. So, you can use the DynamoDB ActiveModel abstraction in V1 alongside this gem.

I would expect that a DynamoDB abstraction would exist as a standalone gem (so that it can be used outside of a Rails context if desired), and this gem would depend on that one. I'm going to close this issue (as it wouldn't be in this gem directly), but the feedback is heard.

**Comment by pas256** [comment]
Thanks Alex. Glad others are thinking the same thing.

Since this issue is closed, what is the best way to track progress and get early alpha access to help with testing?

**Comment by awood45** [comment]
When we can announce something, we will. As far as early access goes, once we have anything we'll release it to GitHub and possibly as a "pre" versioned gem. So in that sense, anyone will be able to test it early on.

**Comment by bramski** [comment]
:+1: Is there an issue I can track for updates on this @awood45 ?  Dynamoid is more or less dead; and Dynamo LocalDB only works on aws api V2, so for our team something here looks like the shortest path to us using DynamoDB on our rails projects.
