### ISSUE TITLE
Clean shutdown procedure is not invoked when the main thread participates in thread pool execution

### ISSUE THREAD

**Issue by pjurewicz** [aws/aws-sdk-rails#123]
`Concurrent::ThreadPoolExecutor` is [initialized](https://github.com/aws/aws-sdk-rails/blob/3c4e4828715a26154a918a5583e08f4f7adebb73/lib/aws/rails/sqs_active_job/executor.rb#L15) with `fallback_policy: :caller_runs`
This means that the work [will be executed in the thread of the caller](https://ruby-concurrency.github.io/concurrent-ruby/1.1.8/file.thread_pools.html), instead of being given to another thread in the pool when the queue of waiting work has reached the maximum size (**backpressure**) and no new threads can be created.
In such case all the exceptions are [rescued](https://github.com/ruby-concurrency/concurrent-ruby/blob/b5e090b9da95c63cd006721ae6a7e594ec78512b/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb#L361) in the `RubyThreadPoolExecutor#run_task`.
This means that `Aws::Rails::SqsActiveJob::Interrupt#run` [rescue block](https://github.com/aws/aws-sdk-rails/blob/f05437103a51dc52c41a4b349d3499580b83a677/lib/aws/rails/sqs_active_job/poller.rb#L57) is not triggered and clean shutdown procedure is not invoked.

**Comment by jterapin** [comment]
Thanks for opening the ticket. We will take a look and get back to you!

**Comment by mostlyobvious** [comment]
One more issue with main thread acting as an additional worker — it needs additional connection to the pooled resources over chosen thread count. For example with explicitly chosen 10 worker threads, the database connection pool would have to be 10 + 1 in order to not experience `ActiveRecord::ConnectionTimeoutError` when backpressure limit is reached.

This is not immediately obvious until experiencing it and reading the code.

**Comment by alextwoods** [comment]
Yeah this is a good point as well.  I had always intended to revisit the use of `caller_runs`.  I believe #124 should make the resource usage more explicit as well.
