### ISSUE TITLE
Middleware not processing jobs on Worker tier with AWS_PROCESS_BEANSTALK_WORKER_REQUESTS=true

### ISSUE THREAD

**Issue by januszm** [aws/aws-sdk-rails#146]
Perhaps I missed something in the documentation, but on the Worker tier, when the environment variable AWS_PROCESS_BEANSTALK_WORKER_REQUESTS=true is set, the tasks are not executed. They are processed only after I manually launch the poller with `bundle exec aws_sqs_active_job --queue default`

```
Starting Poller with options={:threads=>4, :max_messages=>1, :shutdown_timeout=>15, :backpressure=>10, :retry_standard_errors=>true, :queues=>{:default=>"https://sqs.us-east-2.amazonaws.com/123/myapp-staging-default.fifo"}, :logger=>nil, :message_group_id=>"SqsActiveJobGroup", :excluded_deduplication_keys=>["job_id"], :config_file=>#<Pathname:/var/app/current/config/aws_sqs_active_job.yml>, :client=>#<Aws::SQS::Client>, :queue=>"default"}
Polling on: default => https://sqs.us-east-2.amazonaws.com/123/myapp-staging-default.fifo
Processing batch of 1 messages
Running job: 28163508-...
```

I have a queue that I have configured in the yml file mentioned in the log above:

```
queues:
  default: "https://sqs.us-east-2.amazonaws.com/123/myapp-<%= Rails.env %>-default.fifo"
```

If I understand the docs correctly, on AWS EB Worker Tier the poller should start automatically when `AWS_PROCESS_BEANSTALK_WORKER_REQUESTS=true`, but it's not. I'd be great to add a bit more details on how this should work. For example, when using a task queue such as Shoryuken, we know that we have to start the shoryuken process and it'll both poll for messages and will process them (it preloads the Rails application). Here, do we expect the Rails / puma server to process these tasks? Can we confirm that the `aws_sqs_active_job` poller starts automatically when that ENV var is set to true?
Or, does it only work with the EB autogenerated queue, but not with the queues mentioned in the `config/aws_sqs_active_job.yml` file?

**Comment by januszm** [comment]
On a fresh server, this process is missing despite the ENV var is set

```
ruby3.2 /var/app/current/vendor/bundle/ruby/3.2.0/bin/aws_sqs_active_job --queue ...
```

**Comment by alextwoods** [comment]
The `AWS_PROCESS_BEANSTALK_WORKER_REQUESTS` doesn't start the poller - rather it adds middleware to rails that will process HTTP requests sent by the SQS daemon running on the worker.

> Here, do we expect the Rails / puma server to process these tasks?

Yes - rather than starting a poller (which would read of the queue directly) we just add middleware to handle HTTP requests that the SQS daemon on the worker sends.  This does mean that you must [configure the worker](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#using-features-managing-env-tiers-worker-settings) to read from the correct SQS queue that you want to process jobs from - the autogenerated queue default won't work. Re-reading the README it does seem to be missing this information, I can fix that up today.  

How do you have your worker configured?  

From the [EBS worker docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html): 

> Elastic Beanstalk worker environments simplify this process by managing the Amazon SQS queue and running a [daemon process](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-daemon) on each instance that reads from the queue for you. When the daemon pulls an item from the queue, it sends an HTTP POST request locally to http://localhost/ on port 80 with the contents of the queue message in the body.

**Comment by januszm** [comment]
> we just add middleware to handle HTTP requests that the SQS daemon on the worker sends.

Do we have to configure a specific route for the middleware or will it use `POST /` ? I noticed that `POST /` is already used by action_mailbox in this gem.

> This does mean that you must [configure the worker](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#using-features-managing-env-tiers-worker-settings) to read from the correct SQS queue that you want to process jobs from
I just used the default, autogenerated queue. Based on how Shoryuken works, I was expecting this gem to take care of polling additional queues (defined in the yml file) and processing them. If that's not the case, it means I need to set up the poller with the Procfile anyway (which I tried to avoid as in this case that process needs to be somehow disabled on the Web tier).

> How do you have your worker configured?
all default settings, path `/`, autogenerated queue

**Comment by alextwoods** [comment]
The autogenerated queue setting actually creates an entirely new queue for use by this worker.  You would need to configure the worker to read from the queue you want to process jobs from.  (I'll make a documentation update to clarify this).  With this setup, you would need separate worker environments to poll multiple queues (1 per queue) - its a limitation (and intentional design choice) of EBS Workers SQS Daemon.

> Do we have to configure a specific route for the middleware or will it use POST / ? I noticed that POST / is already used by action_mailbox in this gem.

No - the default route should work and shouldn't cause any conflicts.  The [EbsSqsActiveJobMiddleware](https://github.com/aws/aws-sdk-rails/blob/main/lib/aws/rails/middleware/ebs_sqs_active_job_middleware.rb#L21) checks if the request is from the SQS daemon and only processes it if it is (otherwise it hands it off).

**Comment by januszm** [comment]
> No - the default route should work and shouldn't cause any conflicts.

thanks, I found this in the code
https://github.com/aws/aws-sdk-rails/blob/eed32d55aaf3d3c351fb572fbb83d329e2e5dfb4/lib/aws/rails/action_mailbox/engine.rb#L14

and thought / is only used for processing mails, so I understand now it also handles all tasks from the SQS daemon.

Thanks for the tip about EB Workers SQS daemon design, yeah it makes sense to have different worker tier environments for queues of completely different type (long/short running, requiring little or a lot of RAM)

**Comment by januszm** [comment]
Thanks for the update.

I also noticed that setting the queue_adapter in application.rb globally does not work. If you add this
```ruby
config.active_job.queue_adapter = :sqs
```

to `config/application.rb`, it doesn't have effect on ActiveJob:

```ruby
> ApplicationJob.queue_adapter
=>
#<ActiveJob::QueueAdapters::AsyncAdapter:0x00007f6642ead738
  ...
```

but if you set it on the Job level like this:

```ruby
class ApplicationJob < ActiveJob::Base
  self.queue_adapter = :sqs
```

it'll work:

```ruby
> ApplicationJob.queue_adapter
=> #<ActiveJob::QueueAdapters::SqsAdapter:0x00007f0557ee9a40>
```
