### ISSUE TITLE
Event based AWS invocation

### ISSUE THREAD

**Issue by SteffanPerry** [aws/aws-sdk-rails#151]
Currently the gem is very much associated with active job and thus requires the producer of the message to know the class that the message should invoke. This is the way many rails apps work.

Our architecture is more event based. We have multiple rails apps that emit events when a change happens to a model via SNS and One or more queues may subscribe to the topic and listen for the events they care about (In our case we have message attributes describing the event.).

Currently this gem won't work for those service to service events and we are stuck with lambda. Which is fine for many of them but some are long running jobs or require more resources and can get quite pricey vs ecs or ec2.

I'm planning on forking this branch and creating a "raw" invocation. My idea is to use the queue url itself to determine which class should be invoked by a reverse lookup on the queue yaml file. Ideally the whole message not just the body would be passed more lambda ish.

Before I do so I want to make sure I'm not missing something with this gem and possibly I can already do something similar with the current version?

**Comment by mullermp** [comment]
That is a very interesting use case. I'm not sure if generically it makes sense in this gem, but I'm also still trying to understand. If you planned on forking, you could also submit a pull request to add the feature generically and we can discuss it further? Otherwise you can use the fork to solve it.

**Comment by mullermp** [comment]
It seems like lambda is probably your better use case - however instead of lambda processing the request, use active job to kick off a job which does it later on some other process, avoiding long running work. Would that work in your case? There are some existing discussions and issues that have customers using active job from lambda.

**Comment by SteffanPerry** [comment]
That second option might be the route I take. I was trying to avoid having extra complexity of multiple job runners (lambda + solid queue). but maybe it will be worth it in this case
