### ISSUE TITLE
Using SESv2

### ISSUE THREAD

**Issue by OmriSama** [aws/aws-sdk-rails#44]
Hey guys! Only found out about this gem recently and I love it. Thanks for the effort!

I noticed the built in ActionMailer integration uses `SES` instead of the newer `SESv2` API. Is this going to make a huge difference? Are there plans to switch over?
Would you guys accept pull requests?

Thanks!

**Comment by mullermp** [comment]
Hey @OmriSama , thanks for checking this gem out! We plan on making a blog post this week to highlight some of the new features we've added.

Regarding SES vs SESv2, I don't think there's an immediate difference in benefit between them in the context of using ActionMailer. SES hasn't officially announced any sort of deprecation AFAIK. At one point, a customer suggested Pinpoint but we held off because we weren't sure what the long term support plan was. Pinpoint would be interesting because it could support other channels other than email.

We would absolutely take a pull request on this and I can tag this as a feature request.

**Comment by tmedford** [comment]
V2 of api support attachments greater than 10mb. Can we get the added now?

**Comment by mullermp** [comment]
SESv2 support was added last month!
