### ISSUE TITLE
How to send custom parameter to AWS SES?

### ISSUE THREAD

**Issue by hopewise** [aws/aws-sdk-rails#47]
Hello

How to send object below using this gem?
```
{
  "Source":"Mary Major <mary.major@example.com>",
  "Template": "MyTemplate",
  "ConfigurationSetName": "ConfigSet",
  "Destination": {
    "ToAddresses": [ "alejandro.rosalez@example.com"
    ]
  },
  "TemplateData": "{ \"name\":\"Alejandro\", \"favoriteanimal\": \"alligator\" }"
}
```

**Comment by alextwoods** [comment]
To send custom parameters including template to SES I'd recommend not using the action mailer adapter and instead directly using the [SES::Client#send_templated_email](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SES/Client.html#send_templated_email-instance_method) method:
```ruby
# construct an SES client.  Can be done in an initializer or elsewhere
ses = Aws::SES::Client.new

# in your business logic
ses.send_templated_email(source: ..., template: ..., configuration_set_name: ..., template_date: { name: .., favoriteanimal: .... } ) 
```

Alternatively, if you want to take advantage of ActionMailer, I'd recommend using a [Rails Mailer View](https://guides.rubyonrails.org/action_mailer_basics.html#mailer-views) to render the email rather than using SES's templates.

**Comment by hopewise** [comment]
Thanks @alextwoods
