### ISSUE TITLE
SES SDK Rails6 not picking up Region

### ISSUE THREAD

**Issue by makrmark** [aws/aws-sdk-rails#56]
I have set up my SES to initialise per:

```
Rails.application.reloader.to_prepare do
    ActionMailer::Base.add_delivery_method :ses, AWS::SES::Base,
      access_key_id: ENV['AMAZON_ACCESS_ID'],
      secret_access_key: ENV['AMAZON_SECRET_KEY'],
    region: ENV['AWS_REGION']
end

```

However I get an error message that would indicate it is not using my AWS_REGION environment specified.

`The following identities failed the check in region US-EAST-1
`

my AWS_REGION is actually ap-southeast-2

Is there any reason why my region: setting should be getting ignored?

**Comment by makrmark** [comment]
Okay so progress:

I added this configuration per the SDK documentation:

```
server: "email." + ENV['AWS_REGION'] + ".amazonaws.com",
message_id_domain: ENV['AWS_REGION'] + ".amazonses.com"

```

However I then got a credentials error.

After this I got so frustrated I just reverted SES to use the default region for SES which is us-east-1, and removed the additional configuration parameters and it now works just fine.

So I'm not happy that I have to use a different region from everything else but now at least I can send email.

**Comment by mullermp** [comment]
Hey, have you looked at this page? https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html

aws-sdk-rails will create a default instance of `Aws::SES::Client` which will pull credentials automatically from your ENV or from your shared config files. You shouldn't need to provide a custom client and add the delivery method manually unless you want to use a different profile/region than what you already configure.

**Comment by makrmark** [comment]
Hello, I don't have the full SDK installed - only the SES Gem which seems to work a little differently.

Regardless in the end I did get it to pick up my region; but then my credentials did not work. When I just let it connect to the default region those same credentials worked just fine (obviously I had to configure SES on that other region - but it was exactly the same configuration).

Frankly I expended enough needless effort on this that now I've got it working I'm not going to investigate further.

Cheers,
Mark

**Comment by mullermp** [comment]
If you're using `aws-sdk-ses`, it pulls in `aws-sdk-core` as a dependency and it should be loading your credentials automatically using the "credential chain". It shouldn't work any differently for other service gems (because they all depend on `aws-sdk-core`).

Region and credentials are resolved independently. Following the example here (https://github.com/aws/aws-sdk-rails#manually-setting-credentials) you could just set your region and omit credentials; your credentials will be picked up automatically from ~/.aws/credentials.

I am going to close because you mentioned not investigating, but if you decide to, please feel free to re-open and we can help you get that working the way you would like. :D

**Comment by mullermp** [comment]
All service gems (such as aws-sdk-ses) depend on aws-sdk-core and should be loading your credentials automatically using the "credential chain". Region is done similarly is resolved independently of credentials.

It seems like you have your region and credentials in ~/.aws/config and ~/.aws/credentials correctly set up. When you're adding ENV['REGION'] you're overriding those. I think that the easiest thing would be to use something like the example here (https://github.com/aws/aws-sdk-rails#manually-setting-credentials) - you could just set your region in code and omit credentials; your credentials will be picked up automatically like normal.

I am going to close because you mentioned not wanting to investigate anymore, but if you decide to, please feel free to re-open and we can help you get that working the way you would like. :D

**Comment by makrmark** [comment]
Yeah my problem was that the region and credentials were getting picked up (in the end) but using the non-default region for SES was resulting in a credentials problem. The credentials issue went away when I simply reverted to use SES default region.
