### ISSUE TITLE
Setting `log_level` to `:error` does not stop Aws client from outputting

### ISSUE THREAD

**Issue by jshah** [aws/aws-sdk-rails#83]
The `README` says:

> The AWS SDK is configured to use the built-in Rails logger for any SDK log output. The logger is configured to use the :info log level. You can change the log level by setting :log_level in the [Aws.config](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws.html) hash.

```
Aws.config.update(log_level: :debug)
```

However, setting to `:error`: `Aws.config.update(log_level: :error)` does not stop the `Aws` clients from outputting `:info` logs.

```
[Aws::SecretsManager::Client 200 0.204598 0 retries] get_secret_value(secret_id: <hidden>)
```

Only setting the logger to `nil` works:

```
Aws.config.update(logger: nil)
```

I would assume setting `Aws.config.log_level` would apply to all `Aws` modules. Is this the recommended way? Can we update docs to reflect what is recommended here?

**Comment by mullermp** [comment]
Thanks for opening an issue. It should be applying to all Aws modules. What Rails version are you using?

aws-sdk-rails will set `Rails.logger` to Aws.config - https://github.com/aws/aws-sdk-rails/blob/d59a29a15436e5a04d3a2e27364995eefcd3bec8/lib/aws/rails/railtie.rb#L39-L43

Could you also tell me what `Rails.logger` resolves to?

**Comment by jshah** [comment]
@mullermp 

We are on Rails version `6.1.6.1`.

This is whats `Rails.logger` resolves to:

```
[development]> Rails.logger
=> #<ActiveSupport::Logger:0x000000010cef2010 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000010b9052c0 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x000000010cef1f98 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:78900">, @logdev=#<Logger::LogDevice:0x000000010b905248 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @binmode=false, @mon_data=#<Monitor:0x000000010b9050b8>, @mon_data_owner_object_id=65580>>
```

**Comment by jshah** [comment]
We have the following `aws` gems installed:

```
gem 'aws-sdk-athena', '~> 1.2'
gem 'aws-sdk-cloudwatch', require: false
gem 'aws-sdk-ec2', '~> 1'
gem 'aws-sdk-kinesis'
gem 'aws-sdk-lambda', '~> 1.41'
gem 'aws-sdk-rails', '~> 3.6'
gem 'aws-sdk-route53', '~> 1.9.0'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-secretsmanager', '~> 1.21'
gem 'aws-sdk-ses', '~> 1.7.0'
```

**Comment by mullermp** [comment]
Thanks for that. I see your ActiveSupport logger level is 0. I think maybe this is intended behavior? The SDK is sending all information out as `:info` by default, and since your Rails logger level is 0, it will print out to STDOUT as info. Since you changed it to debug, it's sending it to the debug method, and your Rails logger sees that and prints it because it's configured to do so.

So what you would probably want is to keep the SDK default of :info and instead use `config.logger.level = Logger::ERROR` or equivalent in your Rails environment.

**Comment by jshah** [comment]
@mullermp what if I want my Aws `log_level` to be at `:error` and my Rails log_level to be at `:info`? Is that not possible to have them separated?

I think it would be a good addition because Aws logs at `:info` can get very spammy for us so we only want to know when things are erroring.

**Comment by mullermp** [comment]
What's happening is that the Rails logger is configured as the `logger` option for the SDK, so the SDK is using it to log at the level configured (`:info`). Then your Rails logger is configured with level 0 (or `:debug). Rails will log messages and print if the level is equal or higher to the configured level ([documentation](https://guides.rubyonrails.org/debugging_rails_applications.html#log-levels)). The rails logger sees the `:info` logs from the SDK, and it's >= 0, so it outputs. 

If you set Aws log level to :error, and Rails to `:info`, it will still print SDK logs because error is higher than info. What you might want to try is setting the Aws log level to `:debug`, and set your Rails logger to `:info`. That way you won't see Aws logging unless you change to debug logging, but you'll see your info logging in Rails. You could similarly set Aws logging to `:info` the default and change your Rails logging to `:warn`.

I hope this makes sense.

**Comment by jshah** [comment]
@mullermp that makes sense, I just pasted my development configuration levels but in production, we are using `:info` for Rails.

The only question I have is that even if I set my Aws SDK log level below my Rails log level, wouldn't the logs still output because the log itself would still be `:info`? Or do ALL logs from the SDK get set to what I set my Aws config at?

**Comment by mullermp** [comment]
All logs from the SDK will be what you configure log level with in AWS config. Then your Rails logger will determine whether it should output or not based on its level configuration.

**Comment by jshah** [comment]
perfect, thank you! That's everything I need!

**Comment by thomaswitt** [comment]
@mullermp I would like to come back to that question. When ever you use DynamoDB, your logfile gets spammed by every single query

```
12:51:32 logs.1     | [Aws::DynamoDB::Client 200 0.003056 0 retries] query(expression_attribute_names:{"#BUILDERA"=>"hash_key"},expression_attribute_values:{":buildera"=>{s:"TEST#CUR#TEST2"}},key_condition_expression:"#BUILDERA = :buildera",table_name:"_development")
```

I've tried everything in my initializer `config/initializers/aws.rb` , still get spammy loggging in development:

```
aws_config = {
  log_level: Rails.env.production? ? :warn : :info, 
  # Other config stuff like region, credentials, etc. omitted
}
Aws.config.update(aws_config)
```


```
aws_config = {
  log_level: :fatal
}
Aws.config.update(aws_config)
```

```
Aws.config[:log_level] = :fatal
```

Still that spammy logging, producing 100+ lines in Rails per request. Before I write my own custom logger: I don't think that's intended behaviour. Have I overseen something?

**Comment by mullermp** [comment]
What is your current rails logger level?

**Comment by thomaswitt** [comment]
Debug, the standard setting for dev env.
```
>> Rails.logger.level
=> 0
```

**Comment by mullermp** [comment]
The log level config in the SDK is simply the level that the configured logger will send to. Ruby loggers always log messages above the configured level. The SDK log level defaults to info. When you have a debug rails logger, it will output all info level calls, because info is ahead of debug. I think what you are looking to do is to configure the rails logger to debug or info in development and maybe warn in production. You could also change the SDKs level to debug and set the rails logger to info in production if you have other info logs you would like to see.

**Comment by thomaswitt** [comment]
@mullermp So what youre saying is that no matter how I set Aws.config[:log_level], this setting will be ignored? Or what is the purpose of it?. Because for the rest of my rails app, I actually WANT debug as log level. So it means I have to create a custom logger or a log filter?

**Comment by mullermp** [comment]
The SDK will always log to a logger if one is configured, and the log level configuration is the level it is sent to. By default, log level is info, so when given a logger, the SDK will emit info level logs. Since you are configuring debug, Ruby's Logger will emit that. If you want less logging in production, set your production logger above info, or if you keep it at info, set the SDK log level to debug.

**Comment by thomaswitt** [comment]
@mullermp That is really confusing and against my expectations. My expectation, also from other Gems, would be:

```
Aws.config.update(log_level: :warn) # Only log warnings and errors
```

Assuming I want to leave Rails debugging in debug for development like it's the standard but not have my logfile bombarded by hundreds of logs per request, this is my current solution, just FYI:

```
# config/initiallizers/01_log_formatters.rb
  filter_annoying_aws_messages_formatter = proc do |severity, time, progname, msg|
    next if msg.include?('Aws::DynamoDB::Client 200')
    colorize_logs_formatter.call(severity, time, progname, msg) # uses colorize_logs gem
  end

  # Create a logger that writes to STDOUT
  $filtered_aws_logger = ActiveSupport::Logger.new(STDOUT)
  $filtered_aws_logger.formatter = filter_annoying_aws_messages_formatter
```

```
# config/initializers/aws.rb

Aws.config.update(logger: $filtered_aws_logger)
```

**Comment by mullermp** [comment]
I understand and agree with feedback. This is the behavior that existed already. In a future major version, my ideal implementation would be to always log output to various levels such as info, debug, and warn, and have the configured log level be a threshold for when to emit those. So for example, SDK would always log params as debug, deprecated things as warn, operation calls as info, etc, then the log level of info would emit all of those except debug.

**Comment by thomaswitt** [comment]
@mullermp Totally agreed, that would be a great implementation.
